### PR TITLE
docs: update building and installation instructions

### PR DESCRIPTION
**Pull request by pktiuk**
## Proposed changes 

- mark CMake as not recommended way of installation ( Closes: #68 ) 
- Add simple instructions for building `rpm` packages

### CODE REVIEW

**Comment by pktiuk** [comment]
@gombosg   
Could you add instructions for building `rpm` packages?

You could check BTW whether does this way of building package works for you?
```
cmake .. -DCPACK_GENERATOR="DEB"
cmake --build . --target package
```

**Comment by gombosg** [comment]
I'll take a look, yes. 🙂  Though building RPM from a specfile is different than building from Cmake.

**Comment by pktiuk** [comment]
I am just curious how does it work without any explicit configuration for rpm files.

**Comment by gombosg** [comment]
Well, it works like this: https://rpm-packaging-guide.github.io/ 🙂 
I tested the command and it generates a usable RPM file.

**Comment by gombosg** [comment]
I.e. the RPM file installs and runs. I think it's OK to include it in the CI, of course one should prefer distribution RPMs but it's OK.

**Comment by pktiuk** [comment]
It is up to you which method of generating rpm is more suitable in these instructions. Please add the one you prefer.  

Later we could add building this package to our CI.

**Comment by gombosg** [comment]
> Later we could add building this package to our CI.

I think we can add it now, it's very simple to do and looks like a fine additional package for releases.
Do you agree? If so, I'll add it.

**Comment by pktiuk** [comment]
> > Later we could add building this package to our CI.
> 
> I think we can add it now, it's very simple to do and looks like a fine additional package for releases.
> Do you agree? If so, I'll add it.

That's a good idea, but remember about testing how it works on your own fork of AntiMicroX, and be aware that GitHub runners run Ubuntu, not Fedora.  
Do it in separate PR. 

Also remember about pushing to this branch  build instructions for `rpm` ( would like to merge this PR firstly).

**Comment by gombosg** [comment]
Sure, done.

**Review by gombosg — APPROVED** [review]

**Pull request merged**
