### PR TITLE
refactor: remove qglobalshortcut

### LINKED ISSUE #106: Remove qglobalshortcuts
...and global quit shortcut selection in UI plus related code.

- only 1 small functionality tied to it (quit app shortcut - not really useful)
- unlicensed, see https://github.com/mitei/qglobalshortcut/issues/1
- allows doing #99 which is important for Debian packaging

### PR DESCRIPTION
**Pull request by AriaMoradi**
Closes #106

well It built successfully and I opened and tested where "combination of keys for quitting app" is and it didn't crash after a restart and pressing of the set keys.

I think if we remove the ui, we could be done.
we probably can merge and deal with bugs caused by this later!

### CODE REVIEW

**Comment by AriaMoradi** [comment]
I don't know how UI dev works in Qt, so help is needed for the rest of the work.

**Comment by AriaMoradi** [comment]
screenshot_20201203_010715

now It looks like this, I did minimal deletions and just hid the element.

**Comment by AriaMoradi** [comment]
I think this is done, unless we want to hunt the unused code...

**Comment by gombosg** [comment]
Thanks for setting this up! I'll take a deeper look on Friday.

**Comment by gombosg** [comment]
Can you test it like this? I removed most dead code.

**Comment by pktiuk** [comment]
Tested and everything works properly, but I would think about changing default size of settings window, It could be a bit smaller.

I think it looks better in this form.  
image

**Comment by gombosg** [comment]
Yeah it's likely because of the hidden stuff in #115. But I'll try to make it smaller.

**Comment by gombosg** [comment]
Merged, thanks @AriaMoradi for setting this up.

**Pull request merged**
