### PR TITLE
Remove antilib from building targets

### PR DESCRIPTION
**Pull request by pktiuk**
Closes https://github.com/AntiMicroX/antimicrox/issues/98
Closes https://github.com/AntiMicroX/antimicrox/pull/99

### CODE REVIEW

**Comment by pktiuk** [comment]
Could you check if does it work properly in your cases?  
I have successfully built `deb` package for me and installed it without any problems.

**Comment by pktiuk** [comment]
@AriaMoradi  
Could you check how it works on Raspberry Pi ? (Can I assume your Raspberry Pi is still usable?)
And if is our code compilable on Raspi without line `list(APPEND CMAKE_PREFIX_PATH "/usr/lib/arm-linux-gnueabihf")` ( https://github.com/AntiMicroX/antimicrox/issues/102 )

**Comment by AriaMoradi** [comment]
I prefer adding your solution to mine and closing this one because I did a few other improvements. i.e. formatting, separation of concerns,...

**Comment by gombosg** [comment]
OMG and yesterday night I spent 2 hours with this. :D Thanks for solving it!

**Review by gombosg — APPROVED** [review]
Just tell me why this is working so we can learn from it.
- because `xcb` is last in linking list?
- commenting out that 1 line in `tests/CMakeLists.txt`? (Makes little sense)

**Comment by gombosg** [comment]
@AriaMoradi I suggest doing that CMake cleanup with #102.

**Comment by gombosg** [comment]
> And if is our code compilable on Raspi without line list(APPEND CMAKE_PREFIX_PATH "/usr/lib/arm-linux-gnueabihf")

It _has to be_, cmake prefix path can be set from CLI. I'll also test from Fedora.

**Comment by pktiuk** [comment]
> I prefer adding your solution to mine and closing this one because I did a few other improvements. i.e. formatting, separation of concerns,... 

I know, but due to lack of time I decided to start from master, because dealing with one change is quicker (and a bit cleaner) for me. I think we could apply these changes separately.

**Comment by pktiuk** [comment]
> Just tell me why this is working so we can learn from it.
> - because `xcb` is last in linking list?
> - commenting out that 1 line in `tests/CMakeLists.txt`? (Makes little sense)

It was caused by xcb in linking list.

**Comment by AriaMoradi** [comment]
> @AriaMoradi
> Could you check how it works on Raspberry Pi ? (Can I assume your Raspberry Pi is still usable?)
> And if is our code compilable on Raspi without line `list(APPEND CMAKE_PREFIX_PATH "/usr/lib/arm-linux-gnueabihf")` ( #102 )

it worked, for the second one it got merged before I could test it, I'll test building master a will notify you if it had any problems.

**Review by AriaMoradi — APPROVED** [review]

**Comment by pktiuk** [comment]
@gombosg 
Should this commit be classified as `refactor`, `fix` or `chore` ?

**Comment by gombosg** [comment]
I don't care, consider it a chore as it's not visible to end users. Just merge it! :D

**Comment by AriaMoradi** [comment]
Its definitely a "refactor"
We are changing the code without changing its outside behavior

**Pull request merged**
