### PR TITLE
style: Use Markdown for changelog

### PR DESCRIPTION
**Pull request by pktiuk**
Based on idea from: https://github.com/AntiMicroX/antimicrox/pull/83

Could anyone having QT in version at least 5.14 How it looks?

Now changelog should look like this:

### CODE REVIEW

**Comment by AriaMoradi** [comment]
I got this:
```
[ 31%] Building CXX object CMakeFiles/antilib.dir/src/autoprofileinfo.cpp.o
/home/armor/programming/antimicrox/antimicrox/src/aboutdialog.cpp: In member function ‘void AboutDialog::fillInfoTextBrowser()’:
/home/armor/programming/antimicrox/antimicrox/src/aboutdialog.cpp:104:9: error: ‘class Ui::AboutDialog’ has no member named ‘changelogTextEdit’; did you mean ‘changelogPlainTextEdit’?
  104 |     ui->changelogTextEdit->setMarkdown(changelogText);
      |         ^~~~~~~~~~~~~~~~~
      |         changelogPlainTextEdit
make[2]: *** [CMakeFiles/antilib.dir/build.make:2263: CMakeFiles/antilib.dir/src/aboutdialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

I've got qt 5.15

**Comment by gombosg** [comment]
Yeah @pktiuk it's because the `changelogTextEdit` should have the same name in both cases right? :slightly_smiling_face:

**Comment by pktiuk** [comment]
> Yeah @pktiuk it's because the changelogTextEdit should have the same name in both cases right? slightly_smiling_face

Yeah, it may be the case :laughing:

**Review by AriaMoradi — APPROVED** [review]
screenshot_20201129_144416
(don't mind the scrot rectangle artifacts: https://github.com/resurrecting-open-source-projects/scrot/issues/36 
built and tested successfully

**Pull request merged**
