### PR TITLE
build: remove empty directories during uninstallation

### LINKED ISSUE #68: The uninstallation leaves several folders and files behind (cmake)
**Describe the bug**
As the title says, the uninstallation leaves several paths in the system. Below is a list:
```
/usr/include/antimicrox
/usr/share/antimicrox
/usr/share/antimicrox/images
/usr/share/antimicrox/translations
/usr/share/doc/antimicrox
/var/lib/systemd/coredump/core.antimicrox.1000.b432ffc9974547f19a3daace3c1deb63.11690.1603227781000000.zst
```

**To Reproduce**
simply uninstall the program after installing it

**Expected behavior**
All files and directories belonging to the program only, should be removed from the system

**Configuration**
Version of antimicrox: 3.1.2 (from last commit)
System version: Arch Linux

**Additional context**
I don't know if I'm thinking right, but the error may have something to do with the error reported [here](https://github.com/AntiMicroX/antimicrox/issues/57) (this is the last line)

### PR DESCRIPTION
**Pull request by pktiuk**
Closes #68 

## Proposed changes 

- delete directories left after antimicrox uninstallation using cmake

### CODE REVIEW

**Comment by pktiuk** [comment]
Output during uninstallation in my case 
```
Remaining directories to be deleted: /usr/include/antimicrox;/usr/share/doc/antimicrox;/usr/share/antimicrox
```

**Review by gombosg — COMMENTED** [review]
It's ok but this looks like a really brute force way. 😆

**Review by gombosg — APPROVED** [review]

**Comment by pktiuk** [comment]
Which part of this solution is brute force for you?

Entire deleting directories, or maybe one aspect of implementation?

**Comment by gombosg** [comment]
Nah, it's fine. I don't know what it actually deletes and how it works - it's just cmake magic for me.
E.G. in RPM specfiles, you specify files and directories. If you specify a directory then a package owns it, and make sure that it doesn't delete directories it doesn't own.

If you take a look, it's these for Fedora: https://src.fedoraproject.org/rpms/antimicrox/blob/master/f/antimicrox.spec#_92-107

So the directories you listed are fine, correspond to this one.

**Comment by pktiuk** [comment]
This is just looking for directories with paths ending with `antimicrox` among directories where antimicrox had files (but not these containing antimicrox anywhere else just in case if someone had installed antimicrox in directories like `/home/antimicrox/.local/bin`).

I think installing using packages should be a recommended way of installation.   
Currently, our build instructions don't contain instructions for building `rpm` package.

**Pull request closed without merging**
