### PR TITLE
fix: Ensure proper support for breeze icon theme

### LINKED ISSUE #66: Add dark tray icon
**Is your feature request related to a problem? Please describe.**
image
Light tray icon is hard to see in default kde theme.

**Describe the solution you'd like**
Add dark tray icon.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by pktiuk**
Closes #66 

To check how this change works you can switch to `breeze` icon theme.

I have tried to make color of this icon similar to default color used by breeze.

### CODE REVIEW

**Comment by pktiuk** [comment]
Regular one:

old

Icon for Breeze users:

new

**Comment by AriaMoradi** [comment]
> Icon for Breeze users:
> 
> new

well, it looks much better on a light background.

**Comment by pktiuk** [comment]
> well, it might look better on a light background.
Could we see a screenshot comparison with a light theme(background)?

Yes, it would definitely look better at brighter background, but I don't know, how to easily change color of top bar in gnome.

I think this screen shows, that it works properly (at least in case of my environment).   
This is exactly the same icon, but I have changed only brightness here.

**Review by AriaMoradi — APPROVED** [review]

**Comment by AriaMoradi** [comment]
A dark blueish color might look better

**Pull request merged**
