### PR TITLE
Create temp

### PR DESCRIPTION
**Pull request by Daebis**
fresh build, ready to use

Closes #...

## Proposed changes 

- 
- 
- 

----

### CODE REVIEW

**Comment by pktiuk** [comment]
I won't merge this.  
Adding files with links into codebase is not the way git works.

**Comment by Daebis** [comment]
> I won't merge this.
> Adding files with links into codebase is not the way git works.

having no other way to contact the team that maintains this github and wishing to participate
this is the only open channel I found to communicate that I compiled the sources for windows

**Comment by pktiuk** [comment]
@Daebis  
You can put this link in issue mentioning restoring Windows support.

But instead of building app once, it would be better to help with automation of these processes.

You seem to be familiar with Windows, so you could greatly contribute by dealing with more reliable way of installing app by finishing cmake config used for installation AntiMicroX and preparing proper installer for Windows (it would allow easy installation updating and removing AntiMicroX from system).

You could also help with setting up github actions for windows build https://github.com/AntiMicroX/antimicrox/issues/223 it would allow automation of building AntiMicroX and publishing releases (for Linux it is already configured in this way).

**Comment by Daebis** [comment]
i know how install ubuntu and windows 
but not how build a windows package.
i have ask to a friend dev know  c++ make me a package for you.
i have no idea how compiling on windows should be

**Comment by pktiuk** [comment]
You could start from investigating file CMakeLists.txt placed in legacy AntiMicro repository.   
https://github.com/AntiMicro/antimicro/blob/master/CMakeLists.txt 

Especially around https://github.com/AntiMicro/antimicro/blob/master/CMakeLists.txt#L744 because this part of file deals with extracting `.dll` packages required by application.

> i have no idea how compiling on windows should be 

But you somehow compiled it.

**Comment by pktiuk** [comment]
We can continue discussion about creating installer here: https://github.com/AntiMicroX/antimicrox/issues/237  
It may be later easier to track its progress.

**Pull request closed without merging**
