### PR TITLE
fix: fix credits, use Markdown for changelog

### LINKED ISSUE #67: Outdated information in the "Credits" tab in the "About" window
**Describe the bug**
1. Click on "Help"
2. Choose "About"
3. Click on "Credits" tab

**Expected behavior**
You should find up-to-date information about the program being developed

**Configuration**
Version of antimicrox: 3.1.2 (from last commit)
System version: Arch Linux

### PR DESCRIPTION
**Pull request by gombosg**
Closes #67

## Proposed changes 

- Fancy changelog with markdown
- Fix credits text

kép
kép

### CODE REVIEW

**Comment by gombosg** [comment]
Hm, this builds and works for me locally. Why does it fail online? Maybe `QT_CONFIG(textmarkdownreader)` is not implemented in the pipeline?

**Comment by pktiuk** [comment]
This is too cutting edge feature for most of debian-based distros.

As [docs](https://doc.qt.io/qt-5/qtextdocument.html#toMarkdown) say:

>QString QTextDocument::toMarkdown(QTextDocument::MarkdownFeatures features = MarkdownDialectGitHub) const
Returns a string containing a Markdown representation of the document with the given features, or an empty string if writing fails for any reason.
This function was introduced in Qt 5.14.



For example in Ubuntu 20.04 we have:
```
$apt-cache show qttools5-dev
Package: qttools5-dev
Architecture: amd64
Version: 5.12.8-0ubuntu1
```

**Comment by pktiuk** [comment]
I really like this Markdown-based look, but unluckily it would change the required version of QT libraries.

**Comment by gombosg** [comment]
Sadly but reverted. Is the text OK? :slightly_smiling_face:

**Review by pktiuk — APPROVED** [review]
LGTM

**Comment by pktiuk** [comment]
@gombosg 
I think we could think about adding this Markdown-based formatting using 
```cpp
#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)

    ui->changelogTextEdit->setMarkdown(changelogText);
#else
    ui->changelogPlainTextEdit->setPlainText(changelogText);
```

I really liked how this markdown looked. :D

**Pull request merged**
