### PR TITLE
fix: add requirements for QT and sdl version

### PR DESCRIPTION
**Pull request by pktiuk**
Clearly defining our requirements will let us avoid some problems with compatibility.

Like here for example:  https://github.com/AppImage/appimage.github.io/pull/2074

### CODE REVIEW

**Comment by AriaMoradi** [comment]
well I don't know anything about cmake. don't ask me...

**Review by gombosg — APPROVED** [review]
LGTM, built locally, and this version is 3 years old, available everywhere.

**Comment by AriaMoradi** [comment]
> LGTM, built locally, and this version is 3 years old, available everywhere.

**Comment by AriaMoradi** [comment]
I can open and close though..,

**Review by AriaMoradi — APPROVED** [review]

**Pull request merged**
