### PR TITLE
refactor: clean up CMakeLists.txt files

### PR DESCRIPTION
**Pull request by AriaMoradi**
1- reformated them using CLion 
2- cleaned up some redundant code too.

and 
`find_package(SDL2 REQUIRED)` won't work on all systems, so I added it as a comment.
and the fix will be:
```
    # necessary if we use find_package for SDL2
    if(NOT DEFINED SDL2_LIBRARIES)
        set(SDL2_LIBRARIES SDL2::SDL2)
    endif ()
```

### CODE REVIEW

**Comment by pktiuk** [comment]
Everything looks nice, but one thing bothers me.

Why all `if` (`if(` to `if (`) statements have space? This change seems to be a bit strange.

**Comment by AriaMoradi** [comment]
> Everything looks nice, but one thing bothers me.
> 
> Why all `if` (`if(` to `if (`) statements have space? This change seems to be a bit strange.
> 
> Could be these changes undone?

that's happened automatically.

**Comment by AriaMoradi** [comment]
> > Everything looks nice, but one thing bothers me.
> > Why all `if` (`if(` to `if (`) statements have space? This change seems to be a bit strange.
> > Could be these changes undone?
> 
> that's happened automatically.

I could fix them manually

**Comment by pktiuk** [comment]
I think (in a long run) it would be better if it would be done using publicly available tool like https://github.com/cheshirekow/cmake_format (later we could incorporate formatting check into our CI just like in case of code formatting)

But for now we can leave this formatting as it is, only change these if-s with spaces to ones without. They don't seem appropriate (checked examples from CMake sites etc.).

**Comment by AriaMoradi** [comment]
remember to squash when merging to keep git blame cleaner.

**Review by pktiuk — APPROVED** [review]

**Comment by pktiuk** [comment]
In cases like this you can push with force to keep everything clean.  
Force pushing on branches like this one won't hurt anyone. ;)

**Comment by gombosg** [comment]
@AriaMoradi is right, squash & merge is the way to go. :)

**Pull request merged**
