### PR TITLE
fix: Fix /dev/uinput static device node access

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by pktiuk** [comment]
Hi @lnussel could you describe bug you are fixing with this patch? Is there any related issue, or is it something what happened with your installation?

**Comment by lnussel** [comment]
/dev/uinput is a static device node, as such the existing udev rule doesn't work. Not sure it ever worked. Looks like on X11 there is a fallback to Xtest but that doesn't work on Wayland, so uinput ACLs are needed.

**Comment by pktiuk** [comment]
Could you send any link to docs mentioning this?

**Comment by lnussel** [comment]
no but google uinput uaccess leads to eg this https://github.com/ValveSoftware/steam-for-linux/issues/4794

**Comment by pktiuk** [comment]
Thanks for contribution

**Pull request merged**
