### PR TITLE
Icons overhaul

### LINKED ISSUE #61: Icons overhaul
During investigating of issues https://github.com/AntiMicroX/antimicrox/issues/56 and https://github.com/AntiMicroX/antimicrox/issues/58 I have found out, there is a pretty big mess in terms of small icons used by AntiMicroX.

Currently, custom icons are both compiled into binary files (but they are broken because of wrong paths in code) and they are added as a part of system theme called `hicolor`.  
To ensure usage of these icons theme used by app is overridden to be `hicolor`, this solution is very not elegant, duplicates loading of the same icons and can be problematic to use with some themes.
```c++
    updateJoy->setIcon(QIcon::fromTheme(QString::fromUtf8("view_refresh"), QIcon(":/icons/hicolor/16x16/actions/view_refresh.png")));
```

I think it would be better to use icons supplied by system-wide theme, because some of our icon look a bit out of place in some cases, and we should use our old icons as a fallback option in case of problems with themed icons.

I think we could also think about updating some of these icons, because some of them look a bit out of date:  
document_saveedit_clear_listdocument_revert_small...

TL;TR
Things to do:
- [x] use default system-wide icons (https://github.com/AntiMicroX/antimicrox/pull/62 https://github.com/AntiMicroX/antimicrox/pull/71)
- [x] fix fallback links to embedded icons (compiled into binary files of antimicrox) (https://github.com/AntiMicroX/antimicrox/pull/75)
- [x] remove already embedded icons from list of installed elements (https://github.com/AntiMicroX/antimicrox/pull/72)
- [x] add light/dark variants of system tray icon https://github.com/AntiMicroX/antimicrox/issues/66
- [ ] (optional) update default icons

### PR DESCRIPTION
**Pull request by pktiuk**
PR collecting all of minor changes connected with Icons overhaul #61

### CODE REVIEW

**Comment by pktiuk** [comment]
@Hir-design
Would you like to test this branch now?   
Every icon should work now.

**Comment by gombosg** [comment]
I'm happy to test, during the weekend.

**Comment by gombosg** [comment]
Works locally, [building flatpak](https://github.com/flathub/io.github.antimicrox.antimicrox/pull/4).

**Review by gombosg — APPROVED** [review]
LGTM. You can test flatpak by
```
flatpak install --user https://dl.flathub.org/build-repo/30914/io.github.antimicrox.antimicrox.flatpakref
```

**Pull request merged**
