### PR TITLE
docs: cleanup and update of readme

### PR DESCRIPTION
**Pull request by pktiuk**
Created in response to: https://github.com/AntiMicroX/antimicroX/issues/20
## Proposed changes 

- Move building instructions to dedicated Markdown file
- Write simple installation instructions in place of building instructions in main README.md
- update contributors section (now it contains updated list of package maintainers)

### CODE REVIEW

**Comment by pktiuk** [comment]
@OlegPopow
Could you provide simple instructions how to use builds from [chaotic-aur](http://chaotic.bangl.de/chaotic-aur/x86_64/) repository?

**Comment by OlegPopow** [comment]
Sure. I will include links to relevant information, as it is pointless to duplicate what has already been written.

1. https://wiki.archlinux.org/index.php/Pacman#Repositories_and_mirrors
2. https://wiki.archlinux.org/index.php/Mirrors

The exact repository address can be found here.

https://wiki.archlinux.org/index.php/Unofficial_user_repositories#chaotic-aur

**Comment by pktiuk** [comment]
Will this config work properly with
```
pacman -S antimicrox
```
?

**Comment by OlegPopow** [comment]
Yes, if someone adds a repository it will work.

**Pull request merged**
