### PR TITLE
BUILDING.md: correct names for a couple of packages

### PR DESCRIPTION
**Pull request by AriaMoradi**
1- someone just building might not know g++ is in gcc
2- on arch linux libqt5x11extras5-dev is named [qt5-x11extras](https://www.archlinux.org/packages/extra/x86_64/qt5-x11extras/)

### CODE REVIEW

**Review by pktiuk — APPROVED** [review]

**Comment by gombosg** [comment]
@AriaMoradi you have write access, so you can merge this now, right?

**Review by gombosg — APPROVED** [review]
LGTM, I should also add Fedora package names etc.
Generally, if someone wants to build stuff on their own, they should be able to figure out their own package names. They sometimes also change and we just can't keep up with all of them...

**Comment by AriaMoradi** [comment]
> @AriaMoradi you have write access, so you can merge this now, right?

Nope. still "You’re not authorized to merge this pull request."

**Comment by AriaMoradi** [comment]
> LGTM, I should also add Fedora package names etc.
> Generally, if someone wants to build stuff on their own, they should be able to figure out their own package names. They sometimes also change and we just can't keep up with all of them...

As expected, we will when someone complains...

**Pull request merged**
