### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Daebis**
update index 
add windows
make order of index and section more logical

<3

Closes #...

## Proposed changes 

- 
- 
- 

----

### CODE REVIEW

**Comment by pktiuk** [comment]
Hi,  
I don't think this change in readme is needed.  
I can't guarantee that Windows will be restored anytime soon.  
Speed of development depends on my free time (and eventual problems I will aproach during this task).  
Because of this I can't tell how long it will take to ship usable Windows build.

BTW 
This change doesn't look very well

obraz

**Comment by Daebis** [comment]
> Hi,
> I don't think this change in readme is needed.

it's messy, 
So if I can bring some readability, for example with sub-chapters, and a more logical order in the sections, it's always that much more credible.

> I can't guarantee that Windows will be restored anytime soon.
> Speed of development depends on my free time (and eventual problems I will aproach during this task).
> Because of this I can't tell how long it will take to ship usable Windows build.

I'm not asking you to do a windows build in a minute, (I'm on ubuntu)
that's what the phrase "soon" is for
that way people can see that there is something in the works and will be happy with it.

A lot of games have an update announcement with "soon ™" on it.
;)

> 
> BTW
> This change doesn't look very well

for 7, 10 and 11 i still need to understand what is wrong with the title. but the organisation is good.
It would be even better with a sub-chapter. 


could you please restore this branch? you would be nice

**Comment by pktiuk** [comment]
>> Hi,
>> I don't think this change in readme is needed.

> it's messy, 
> So if I can bring some readability, for example with sub-chapters, and a more logical order in the sections, it's always that much more credible.

I don't think we need separate entry in table of contents for these short entries.  
Moreover, in case of adding new entry (for example when someone will create package for another distro) we would have to edit table of contents.  
I want to leave readme this way (in [our website](https://github.com/AntiMicroX/antimicrox.github.io) we will think about nicer alignments and order of installation guides, but that part still needs to wait).

But reordering of these package instructions is a good idea.

I could deal wit this tomorrow

**Comment by Daebis** [comment]
why do you use "**we**" while you only talk to yourself ?  :/


in order of use windows and ubuntu are logically in the lead.

and yes, modifying a readme file for new entries would not be bad, (if github allows sub chapters like the ubuntu doc) 

it's not like it's long.
It's not like it's a long process, and anyone without much knowledge can do it. just validate afterwards.

**Comment by pktiuk** [comment]
I am not the only maintainer of this repo.  
Currently, I am the most active one, because I have more free time now.

**Pull request closed without merging**
