### PR TITLE
feat: Restore Windows build

### LINKED ISSUE #4: Restore Windows installer
This project requires installer for Windows.

Original [antimicro](https://github.com/AntiMicro/antimicro) was compiled on Windows, but this fork doesn't have this feature yet.
Most of required components are already included in antimicro's repository.

It would be nice to also add portable version of AntiMicroX, it was done [there](https://github.com/AntiMicro/antimicro/blob/master/BuildOptions.md)

Things to do:
- [ ] compile AntimicroX on Windows
- [ ] Add build instructions to README
- [ ] Add building and uploading `exe` to github actions on release

This issue is migration of original issue https://github.com/juliagoda/antimicroX/issues/131 from legacy AntiMicroX repo.

### PR DESCRIPTION
**Pull request by gombosg**
Closes #4 

This is a long project. It already configures, generates UI files and gets to about 30% build. From here on, it's a matter of fixing build errors one by one and re-adding packaging stuff like Windows icons and installers.

It's easy because I can just take a look at `antimicro` code and copy over whatever's needed, but it's also long and risky (however much I work on this, it may not be successful...).

### CODE REVIEW

**Comment by gombosg** [comment]
I also merged qglobalshortcut removal into here, it'll end up on master soon anyway.

**Comment by AriaMoradi** [comment]
It's better to not touch .gitignore @gombosg

**Comment by gombosg** [comment]
Could you elaborate? It's there to exclude build-generated stuff from git. I mostly know what I'm doing. :)

**Comment by pktiuk** [comment]
I am not sure about this way of working with restoring windows support.  
I think it would be better to have a single branch with fixes for windows and merge to it via PR to keep history clean (and maybe rebase it from time to time), or maybe we should just merge these changes to master (like this FindSFML2.cmake).

**Comment by gombosg** [comment]
I don't see where the problem is, this is standard git workflow. These commits will be squashed anyway on merge. Merging master into a feature branch every now and then is standard procedure to keep them updated. (At least we do it a t `$DAYJOB` :slightly_smiling_face:)

(And personally I find it much better than rebasing because rebasing modifies branch history and makes it nearly impossible to collaborate on a branch.)

I'm not sure if merging half/non-working code to master is a good idea. If the project turns out to be not working after all or is abandoned, then we are either left with dead code in master or we have to revert. So we don't win much by that.

**Comment by pktiuk** [comment]
> These commits will be squashed anyway on merge. Merging master into a feature branch every now and then is standard procedure to keep them updated. (At least we do it a t $DAYJOB slightly_smiling_face)

I am not sure whether squashing so many changes into one commit is a good idea, It will make a history of development not very clear.   
That's why we are using rebase when possible at my $DAILYJOB :wink:   

> rebasing modifies branch history and makes it nearly impossible to collaborate on a branch

Yes, it makes nearly impossible collaborating when many people are working on a single branch, but currently there are only 3 of us and we could notify each other when we want to rebase to get some needed change from master. (we don't have to do it very often).

**Comment by gombosg** [comment]
If this ever gets merged, I promise to make an interactive rebase, squashing unnecessary commits. :smile:

**Comment by Yay-mod** [comment]
can you make a version that work on windows subsystem for linux

**Comment by pktiuk** [comment]
Do you remember why quit shortcut functionality is removed here?

**Comment by pktiuk** [comment]
You started this restoration well, but it may be difficult to merge it (due to big changes I've made during last year).  
I will try to do it in my way.

**Comment by pktiuk** [comment]
I won't delete this branch yet, because there may be still something useful

**Pull request closed without merging**
